# Generated by Django 5.0.6 on 2024-09-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justBlogIt_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='postTitle',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
