# Generated by Django 5.0.6 on 2024-09-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justBlogIt_api', '0002_notification_posttitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
