# Generated by Django 5.0.6 on 2024-09-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justBlogIt_api', '0003_alter_post_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='postImage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
