# Generated by Django 5.0.6 on 2024-09-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justBlogIt_api', '0004_alter_notification_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notificationType',
            field=models.CharField(choices=[('follow', 'Follow'), ('unfollow', 'Unfollow'), ('Comment', 'comment'), ('Reply', 'reply'), ('None', 'none'), ('Like', 'like'), ('unlike', 'Unlike')], default='None', max_length=32),
        ),
    ]
