# Generated by Django 5.0.6 on 2024-09-11 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justBlogIt_api', '0005_alter_notification_notificationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='createdAt',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
